In [1]:
# How to ADD numerical value to each electment of a matrix
def operation_metrices_add():
    print()
    print(format('How to add a constant to each electment of a matrix',
                 '*^72'))

    # Load library
    import numpy as np

    # Create two vectors
    matrixA = np.array([[2, 3, 23],
                       [5, 6, 25],
                       [8, 9, 28]])


    # Create a function that adds 100 to something
    add_100 = lambda i: i + 100

    # Create a vectorized function
    vectorized_add_100 = np.vectorize(add_100)

    # Apply function to all elements in matrix
    print(); print(vectorized_add_100(matrixA))

operation_metrices_add()


**********How to add a constant to each electment of a matrix***********

[[102 103 123]
 [105 106 125]
 [108 109 128]]
