In [2]:
# How to Divide each electment of a matrix by a numerical value
def operation_metrices_div():
    print()
    print(format('How to divide each element of a matrix by a numerical value',
                 '*^72'))

    # Load library
    import numpy as np

    # Create two vectors
    matrixA = np.array([[2, 3, 23],
                       [5, 6, 25],
                       [8, 9, 28]])

    # Create a function that adds 100 to something
    add_100 = lambda i: i / 9

    # Create a vectorized function
    vectorized_add_100 = np.vectorize(add_100)

    # Apply function to all elements in matrix
    print(); print(vectorized_add_100(matrixA))

operation_metrices_div()


******How to divide each element of a matrix by a numerical value*******

[[0.22222222 0.33333333 2.55555556]
 [0.55555556 0.66666667 2.77777778]
 [0.88888889 1.         3.11111111]]
