In [1]:
## How to impute missing class labels in Python 
def imputr_missing_class_labels():
    print()
    print(format('How to impute missing class labels in Python', '*^82'))
    import warnings
    warnings.filterwarnings("ignore")

    # Load libraries
    import numpy as np
    from sklearn.preprocessing import Imputer

    # Create Feature Matrix With Missing Values
    X = np.array([[2,       2.10, 1.45],
                  [1,       1.18, 1.33],
                  [2,       1.22, 1.27],
                  [0,       -0.21, -1.19],
                  [np.nan,  0.87, 1.31],
                  [np.nan, -0.67, -0.22]])

    # Create Imputer object
    imputer = Imputer(strategy='most_frequent', axis=0)

    # Fill missing values with most frequent class
    print(); print(X)
    print(); print(imputer.fit_transform(X))

imputr_missing_class_labels()


*******************How to impute missing class labels in Python*******************

[[ 2.    2.1   1.45]
 [ 1.    1.18  1.33]
 [ 2.    1.22  1.27]
 [ 0.   -0.21 -1.19]
 [  nan  0.87  1.31]
 [  nan -0.67 -0.22]]

[[ 2.    2.1   1.45]
 [ 1.    1.18  1.33]
 [ 2.    1.22  1.27]
 [ 0.   -0.21 -1.19]
 [ 2.    0.87  1.31]
 [ 2.   -0.67 -0.22]]


C:\Users\DELL\anaconda\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
