In [1]:

## How to MULTIPLY numerical value to each electment of a matrix
def operation_metrices_mul():
    print()
    print(format('How to multiply something to each electment of a matrix',
                 '*^72'))

    # Load library
    import numpy as np

    # Create two vectors
    matrixA = np.array([[2, 3, 23],
                       [5, 6, 25],
                       [8, 9, 28]])

    # Create a function that multipies 100 to something
    multiply_100 = lambda i: i * 100

    # Create a vectorized function
    vectorized_multiply_100 = np.vectorize(multiply_100)

    # Apply function to all elements in matrix
    print(); print(vectorized_multiply_100(matrixA))

operation_metrices_mul()


********How to multiply something to each electment of a matrix*********

[[ 200  300 2300]
 [ 500  600 2500]
 [ 800  900 2800]]
