In [1]:
# How to Reshape a Numpy Array or Matrix
def reshape_numPy_array():
    print()
    print(format('How to Reshape a Numpy Array', '*^52'))

    # Load library
    import numpy as np

    # Create a 4x3 matrix
    matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])

    # Reshape matrix into 2x6 matrix
    print()
    print(matrix.reshape(2, 6))

    print()
    print(matrix.reshape(3, 4))

    print()
    print(matrix.reshape(6, 2))

reshape_numPy_array()


************How to Reshape a Numpy Array************

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
